apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
    type: web-application
  name: nginx-pod
spec:
  containers:
    - image: nginx:1.25.4
      name: nginx-pod
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      ports:
        - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
