apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-access-managed-identity-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Replace with your Azure Managed Identity client ID
    azure.workload.identity/tenant-id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Replace with your Azure tenant ID
